DROP TABLE IF EXISTS `debts`;
--;;
DROP TABLE IF EXISTS `debt_table`;
--;;
DROP TABLE IF EXISTS `transaction_owners`;
--;;
DROP TABLE IF EXISTS `transaction_items`;
--;;
DROP TABLE IF EXISTS `transactions`;
--;;
DROP TABLE IF EXISTS `items`;
--;;
DROP TABLE IF EXISTS `vendors`;
--;;
DROP TABLE IF EXISTS `users`;
