(ns cuenta.components.bootstrap
  (:require [cljsjs.react-bootstrap]
            [goog.string :as g-string]
            [reagent.core :as r]))

(def back-arrow (g-string/unescapeEntities "&lArr;"))
(def button (r/adapt-react-class (.-Button js/ReactBootstrap)))
(def checkbox (r/adapt-react-class (.-Checkbox js/ReactBootstrap)))
(def col (r/adapt-react-class (.-Col js/ReactBootstrap)))
(def control-label (r/adapt-react-class (.-ControlLabel js/ReactBootstrap)))
;(def control-label (.-ControlLabel js/ReactBootstrap))
(def form (r/adapt-react-class (.-Form js/ReactBootstrap)))
(def form-control (r/adapt-react-class (.-FormControl js/ReactBootstrap)))
(def form-control-feedback (r/adapt-react-class (.-FormControl.Feedback js/ReactBootstrap)))
(def form-group (r/adapt-react-class (.-FormGroup js/ReactBootstrap)))
(def grid (r/adapt-react-class (.-Grid js/ReactBootstrap)))
(def glyphicon (r/adapt-react-class (.-Glyphicon js/ReactBootstrap)))
(def input-group (r/adapt-react-class (.-InputGroup js/ReactBootstrap)))
(def input-group-addon (r/adapt-react-class (.-InputGroup.Addon js/ReactBootstrap)))
(def left-arrow (g-string/unescapeEntities "&larr;"))
(def modal (r/adapt-react-class (.-Modal js/ReactBootstrap)))
(def modal-body (r/adapt-react-class (.-Modal.Body js/ReactBootstrap)))
(def modal-dialog (r/adapt-react-class (.-Modal.Dialog js/ReactBootstrap)))
(def modal-footer (r/adapt-react-class (.-Modal.Footer js/ReactBootstrap)))
(def modal-header (r/adapt-react-class (.-Modal.Header js/ReactBootstrap)))
(def modal-title (r/adapt-react-class (.-Modal.Title js/ReactBootstrap)))
(def menu-item (r/adapt-react-class (.-MenuItem js/ReactBootstrap)))
(def nav (r/adapt-react-class (.-Nav js/ReactBootstrap)))
(def nav-item (r/adapt-react-class (.-NavItem js/ReactBootstrap)))
(def navbar (r/adapt-react-class (.-Navbar js/ReactBootstrap)))
(def navbar-collapse (r/adapt-react-class (.-Navbar.Collapse js/ReactBootstrap)))
(def navbar-header (r/adapt-react-class (.-Navbar.Header js/ReactBootstrap)))
(def navbar-brand (r/adapt-react-class (.-Navbar.Brand js/ReactBootstrap)))
(def nbsp (g-string/unescapeEntities " "))
(def panel (r/adapt-react-class (.-Panel js/ReactBootstrap)))
(def right-arrow (g-string/unescapeEntities "&rarr;"))
(def row (r/adapt-react-class (.-Row js/ReactBootstrap)))
(def table (r/adapt-react-class (.-Table js/ReactBootstrap)))
